#############################################################
#                                                           #
# Copyright (c) 2022, University of California, Los Angeles #
#                                                           #
# Authors: Kenny J. Chen, Brett T. Lopez                    #
# Contact: kennyjchen@ucla.edu, btlopez@ucla.edu            #
#                                                           #
#############################################################

/**:
  ros__parameters:

      dlo/version: 1.4.3

      dlo/adaptiveParams: true

      dlo/imu: false
      dlo/gravityAlign: false

      dlo/odomNode/odom_frame: "world"   #odom
      dlo/odomNode/child_frame: "lidar"    #base_link

      dlo/mapNode/publishFullMap: false   #true
      dlo/mapNode/publishFreq: 1.0
      dlo/mapNode/leafSize: 0.25
